---
- name: add email aliases
  lineinfile:
    dest: /etc/aliases
    line: "{{ item.name }}: {{ item.alias }}"
    regexp: "^#?{{ item.name }}:"
  with_items: '{{ mail_aliases }}'
  notify: rebuild mail aliases

- name: remove email aliases
  lineinfile:
    dest: /etc/aliases
    regexp: "^#?{{ item.name }}:"
    state: absent
  with_items: '{{ mail_aliases_to_remove }}'
  notify: rebuild mail aliases
